// Vercel build script — generates firebase-config.js from environment variables
// Run automatically by Vercel before deploying.
// Set these env vars in: Vercel Dashboard > Project > Settings > Environment Variables

const fs = require('fs');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('Missing Firebase env vars:', missing.join(', '));
  process.exit(1);
}

const config = `// Auto-generated by build.js — do not edit manually
const firebaseConfig = {
  apiKey:            "${process.env.FIREBASE_API_KEY}",
  authDomain:        "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId:         "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket:     "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${process.env.FIREBASE_APP_ID}",
  measurementId:     "${process.env.FIREBASE_MEASUREMENT_ID || ''}"
};
`;

fs.writeFileSync('firebase-config.js', config, 'utf8');
console.log('✓ firebase-config.js generated successfully.');
